### ISSUE TITLE
Which Xbox

### ISSUE THREAD

**Issue by DarrenRainey** [mborgerson/nxdk-rdt#11]
Just found this project and was wondering if this is for the original xbox, the xbox 360 or the xbox one

**Comment by mborgerson** [comment]
This is a development tool for the original Xbox. If you're interested in contributing to the emulator project, please check out [XQEMU](https://github.com/xqemu/xqemu).

**Comment by JayFoxRox** [comment]
This should probably be fixed in the README.md
You should also consider adding tags to this repo to get more exposure :)

**Comment by mborgerson** [comment]
@JayFoxRox not a bad idea, thanks!
